local youtube=dofile('lua/youtube.lua')
assert(youtube.is_url('https://youtube.com/watch?v=abc'))
assert(youtube.is_url('https://www.youtube.com/shorts/abc'))
assert(youtube.is_url('https://music.youtube.com/watch?v=abc'))
assert(youtube.is_url('https://youtu.be/abc?t=2'))
assert(youtube.is_url('https:/youtu.be/abc'))
assert(not youtube.is_url('https://youtube.example/watch?v=abc'))
assert(not youtube.is_url('song by artist'))
assert(youtube.target('song by artist')=='ytsearch8:song by artist')
assert(youtube.target('https://youtu.be/abc')=='https://youtu.be/abc')
assert(youtube.target('https:/youtu.be/abc')=='https://youtu.be/abc')
assert(youtube.watch_url('a-b_c')=='https://www.youtube.com/watch?v=a-b_c')
assert(not pcall(youtube.watch_url,'bad&id'))
assert(youtube.open_command('OSX64','abc')=="/usr/bin/open 'https://www.youtube.com/watch?v=abc'")
assert(youtube.open_command('Linux','abc')=="/usr/bin/xdg-open 'https://www.youtube.com/watch?v=abc'")
assert(youtube.open_command('Win64','abc'):match('Start%-Process'))
print('YouTube query handling passed: search terms and direct URLs')
